name: scconecta_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.9.0' # Certifique-se de que há 2 espaços antes de "sdk"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  table_calendar: ^3.1.0
  google_fonts: ^7.0.2
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.3.0
  http: ^1.1.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  mask_text_input_formatter: ^2.9.0
  google_sign_in: 6.2.1
  carrier_info: 2.0.8
  permission_handler: ^11.3.1
  network_info_plus: ^6.0.0
  speed_test_dart: ^1.0.5+0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/